In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
#importing the datasets
datasets=pd.read_csv('energydata_complete.csv')

In [5]:
datasets.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [7]:
#the shape of the datasets
datasets.shape

(19735, 29)

In [8]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [9]:
#fitting simple linear regression
simple_linear_reg_datasets= datasets[['T2','T6']].sample(15,random_state=2)

In [11]:
simple_linear_reg_datasets

T2         T6
1117   17.426667  -4.238889
16275  22.760000  14.690000
13272  21.230000   8.926667
3160   21.100000   7.690000
19210  21.856667  10.800000
8260   17.356667   5.000000
12299  19.000000   5.300000
13505  22.700000  17.133333
12913  19.593333   7.545000
17788  21.890000   9.190000
17894  21.500000   5.160000
7665   19.142857   0.937500
10165  18.000000   0.200000
18809  22.400000  16.833333
8737   17.066667   1.900000

In [18]:
X= datasets['T2']
y= datasets['T6']

In [19]:
corr_matrix = np.corrcoef(X,y)

In [20]:
corr=corr_matrix[0,1]

In [21]:
r_sq = corr**2

In [22]:
r_sq

0.6418990830855498

In [23]:
round(r_sq, 2)

0.64

In [34]:
#dropping date and lights from the datasets
datasets= datasets.drop(['date','lights'], axis=1)

In [35]:
datasets.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 27 columns]

In [37]:
#Normalizing of datasets using MiniMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_datasets = pd.DataFrame(scaler.fit_transform(datasets),columns=datasets.columns)
features_datasets = normalised_datasets.drop(columns=['Appliances','T2'])
target = normalised_datasets['Appliances']

In [39]:
#splitting the datasets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features_datasets, target, test_size=0.33, random_state=1)

In [40]:
#building the model
from sklearn.linear_model import LinearRegression 
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

LinearRegression()

In [41]:
predicted_values = linear_model.predict(X_test)

In [42]:
predicted_values

array([0.06270836, 0.09093744, 0.11354047, ..., 0.06324181, 0.10860377,
       0.12692974])

In [43]:
#evaluating the model
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)

In [44]:
mae

0.05026341472443582

In [45]:
round(mae, 2)

0.05

In [51]:
# importing r2_score module
from sklearn.metrics import r2_score, mean_squared_error

# predicting the accuracy score
score=r2_score(y_test,predicted_values)
mean_squared_error=mean_squared_error(y_test,predicted_values)

In [54]:
score
round(score, 2)

0.15

In [53]:
mean_squared_error
round(mean_squared_error, 3)

0.008

In [75]:
from sklearn import linear_model
ridge_reg = linear_model.Ridge (alpha = .4)

In [76]:
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.4)

In [77]:
predicted_value = ridge_reg.predict(X_test)

In [78]:
predicted_value

array([0.06260441, 0.09133522, 0.11314952, ..., 0.06291084, 0.10880803,
       0.12766081])

In [79]:
mean_squared_error=mean_squared_error(y_test,predicted_value)

In [80]:
mean_squared_error

0.007793276454886076

In [85]:
from sklearn import linear_model
ridge_reg = linear_model.Lasso (alpha = 0.001)


In [86]:
ridge_reg.fit(X_train, y_train)

Lasso(alpha=0.001)

In [87]:
predicted_value = ridge_reg.predict(X_test)

In [88]:
predicted_value

array([0.07433549, 0.088924  , 0.0877082 , ..., 0.07403774, 0.09753036,
       0.09946288])

In [89]:
mean_squared_error=mean_squared_error(y_test,predicted_value)

TypeError: 'numpy.float64' object is not callable